# notARepository: "quit"
git:
  overrideGpg: true
os:
  editPreset: nvim
gui:
  showBottomLine: true
  nerdFontsVersion: "3"
  border: rounded
  theme:
    activeBorderColor:
      - "#00ff00" # green
      - "bold"
    selectedLineBgColor:
      - "#5f8700"
    unstagedChangesColor:
      - "#ff0000" # red
    searchingActiveBorderColor:
      - "#000000"
      - "bold"
    optionsTextColor:
      - "#ffd7af"
    inactiveBorderColor:
      - "#808080" # gray
    defaultFgColor:
      - "default"
    cherryPickedCommitFgColor:
      - "#ffd7af"
    cherryPickedCommitBgColor:
      - "#ff8787"
